### ISSUE TITLE
M2: Containerized Application

### ISSUE THREAD

**Issue by cs-uche** [UBC-MDS/airline-customer-satisfaction-predictor#19]
- [x] Create a conda-lock file(based on the linux environment)
- [x] Create a Dockerfile
- [x] Create a container
- [x] Test the Docker file locally

**Comment by AzinPiran** [comment]
# Updates on the Containerization Branch  

Hi everyone,  

I’ve created a new branch called **containerization** and made some key updates compared to our previous main branch. Please take a look at pull request #24

**Comment by AzinPiran** [comment]
I've pinned all of the packages' version and tested our notebook, it is working.

**Comment by AzinPiran** [comment]
To ensure the seamless deployment and management of our containerized application, we also need to include a docker-compose.yml file in the repository. This will help us easily define and run multi-container Docker applications I am going to add this file and add another pull request.
