### ISSUE TITLE
M2: Create a Docker Compose file

### ISSUE THREAD

**Issue by cs-uche** [UBC-MDS/airline-customer-satisfaction-predictor#27]
- [x] Ensure all the dependencies in the environment.yml are up to date
- [x] Create the docker compose file

**Comment by cs-uche** [comment]
This issue was a dependency for #20 (task -  Update Workflow to automatically add tag). Therefore it was started and will be completed once the `environment.yml` file is up to date.

**Comment by cs-uche** [comment]
This task has not been completed as the first point `Ensure all the dependencies in the environment.yml are up to date` is not completed.

Analysis is still being performed which means that the environment file could change to reflect new dependencies creating a waterfall of changes in other files including the compose file

**Comment by cs-uche** [comment]
@AzinPiran please see the above comment

**Comment by AzinPiran** [comment]
@cs-uche , Thanks for your clarification, you are right, it's better to wait to finish the analyses first and then create this file.

**Comment by cs-uche** [comment]
Task 1: Updating dependencies was contingent on resolving issue #16, which has now been resolved. The dependencies have been successfully updated, and the GitHub Actions workflow has completed without errors. This issue can now be resolved.

**Comment by cs-uche** [comment]
Image of the recent successful run below:
![Image](https://github.com/user-attachments/assets/69bb31e9-cd1c-4f14-ad90-30ddf327a6bc)
