### ISSUE TITLE
M3: Modelling (model_training.py)

### ISSUE THREAD

**Issue by HrayrMuradyan** [UBC-MDS/airline-customer-satisfaction-predictor#36]

**Comment by AzinPiran** [comment]
This script will handle model creation, training, cross-validation, and hyperparameter tuning.

**Comment by cs-uche** [comment]
> This script will handle model creation, training, cross-validation, and hyperparameter tuning.

The script does not explicitly include a cross validation step but does include cross validation in the hyper parameter tuning. It is now visible on the remote please view the #44
