### ISSUE TITLE
M3: Model Evaluation Script (model_evaluation.py)

### ISSUE THREAD

**Issue by HrayrMuradyan** [UBC-MDS/airline-customer-satisfaction-predictor#38]

**Comment by cs-uche** [comment]
> This module will handle evaluating the model on unseen data, calculating performance metrics, and plotting confusion matrix, precision-recall curve, and ROC curve.

Yes the script evaluates the model performance on unseen data, calculates performance metric **although the metric calculated is solely accuracy, please confirm that this is the only metric required for the analysis**. Additionally, it saves the confusion matrix and performance metric as csvs and the PR and ROC curve as pngs.

**Comment by cs-uche** [comment]
Please view the Pull Request at #44 for updates to the scripts
