### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by cs-uche** [UBC-MDS/airline-customer-satisfaction-predictor#4]
Good job! 

The only thing is that:
Method -> Model section at the top of the document does not match the model training we do. We should fix it.

Also, please refer to my issue and provide feedback about the suggestions.

_Originally posted by @HrayrMuradyan in https://github.com/UBC-MDS/airline-customer-satisfaction-predictor/issues/3#issuecomment-2492879862_

**Comment by cs-uche** [comment]
Great Point, deciding on a model before completing feature exploration should be discouraged. Additionally since the KNN Classifier can be used for Classification tasks it was included in the section Comparison Models

**Comment by cs-uche** [comment]
It was however commented out because the models took too long to run on my system this might because our current features need some feature engineering to optimize them for that classifier or my local system is not optimized for such tasks.

**Comment by cs-uche** [comment]
Consider uncommenting and run it on your system before merging

**Comment by AzinPiran** [comment]
problem was fixed.
