### ISSUE TITLE
M4: Address feedback to improve the project

### ISSUE THREAD

**Issue by AzinPiran** [UBC-MDS/airline-customer-satisfaction-predictor#50]

**Comment by AzinPiran** [comment]
create a file called CHANGELOG.md that lives in the root of your repository. In this file describe any improvements we made to the project based on feedback, and point to evidence of these improvements.

**Comment by HrayrMuradyan** [comment]
Hi all,

Please work on the branch: **review-changes** for this part of the Milestone.
Here is the pull request:

https://github.com/UBC-MDS/airline-customer-satisfaction-predictor/pull/52

Leave it unmerged until all changes are done and approved.
