### ISSUE TITLE
Evaluation Branch Feedback Needed

### ISSUE THREAD

**Issue by shengjiayuu** [UBC-MDS/airline-customer-satisfaction-predictor#9]
Please review the new branch, "evaluation," as I’m not sure if I’m on the right track. If everything looks good, I’ll wrap up with the discussion. Feel free to provide your suggestions if anything needs to be changed; I can fix it later as well.

**Comment by cs-uche** [comment]
@shengjiayuu please create a Pull Request and assign it

**Comment by AzinPiran** [comment]
Sure @shengjiayuu , I am going to pull your changes and review it, and also I will try to create a conda-Lock file.

**Comment by cs-uche** [comment]
@shengjiayuu I pulled your branch to test it out and included my suggestions in the pull request(pr) you created

**Comment by AzinPiran** [comment]
evaluation completed, we added a new metric to select the best model.
